Resolve static analysis issues
laravel/laravel pull request #5581
Opened 2021-04-10 21:56 UTC by andriichuk

Hi! I am using static code analysis tools like Larastan and Psalm. How about fixing some small issues?

Environment: Laravel Sail

```shell
./vendor/bin/sail php artisan --version // Laravel Framework 8.35.1
```

Run Psalm with Laravel Plugin (https://github.com/psalm/psalm-plugin-laravel) and `errorLevel="3"`:

```shell
./vendor/bin/sail php ./vendor/bin/psalm
```

Result:

```
ERROR: NonInvariantDocblockPropertyType - app/Exceptions/Handler.php:24:15 - Property App\Exceptions\Handler::$dontFlash has type array<array-key, mixed>, not invariant with Illuminate\Foundation\Exceptions\Handler::$dontFlash of type array<array-key, string> (see https://psalm.dev/267)
    protected $dontFlash = [

ERROR: NonInvariantDocblockPropertyType - app/Http/Middleware/TrustProxies.php:22:15 - Property App\Http\Middleware\TrustProxies::$headers has type int, not invariant with Fideloper\Proxy\TrustProxies::$headers of type int|null|string (see https://psalm.dev/267)
    protected $headers = Request::HEADER_X_FORWARDED_FOR | Request::HEADER_X_FORWARDED_HOST | Request::HEADER_X_FORWARDED_PORT | Request::HEADER_X_FORWARDED_PROTO | Request::HEADER_X_FORWARDED_AWS_ELB;

ERROR: NonInvariantDocblockPropertyType - app/Models/User.php:19:15 - Property App\Models\User::$fillable has type array<array-key, mixed>, not invariant with Illuminate\Database\Eloquent\Concerns\GuardsAttributes::$fillable of type array<array-key, string> (see https://psalm.dev/267)
    protected $fillable = [
```

Run Larastan with `level: 8`:

```shell
./vendor/bin/sail php ./vendor/bin/phpstan analyse
```

Result:

```
 ------ ------------------------------------------------------------------------------------------------------------------ 
  Line   Http/Middleware/Authenticate.php                                                                                  
 ------ ------------------------------------------------------------------------------------------------------------------ 
  17     Method App\Http\Middleware\Authenticate::redirectTo() should return string|null but return statement is missing.  
 ------ ------------------------------------------------------------------------------------------------------------------ 
```

And remove unused class import:

```diff
- use Illuminate\Contracts\Auth\MustVerifyEmail;
```

2021-04-10 22:11 UTC, GrahamCampbell requested changes

2021-04-10 22:11 UTC, GrahamCampbell commented on app/Http/Middleware/TrustProxies.php
> +     * @var int|string|null
This is not a correct change.

2021-04-10 22:11 UTC, GrahamCampbell commented on app/Models/User.php
> -use Illuminate\Contracts\Auth\MustVerifyEmail;
This is not a correct change.

2021-04-10 22:12 UTC, GrahamCampbell commented
The import is intentionally unused and included. This is why StyleCI is configured to not remove it... https://github.com/laravel/laravel/blob/8.x/.styleci.yml#L4.

2021-04-10 22:16 UTC, andriichuk commented on app/Models/User.php
> -use Illuminate\Contracts\Auth\MustVerifyEmail;
Restored. Thanks

2021-04-10 22:21 UTC, GrahamCampbell commented on app/Http/Middleware/TrustProxies.php
> +     * @var int|string|null
Please revert this change. The static analyzer is wrong.

2021-04-10 22:24 UTC, andriichuk commented on app/Http/Middleware/TrustProxies.php
> +     * @var int|string|null
But what is wrong? I just follow the parent class type declaration

https://github.com/fideloper/TrustedProxy/blob/master/src/TrustProxies.php#L28
https://psalm.dev/docs/running_psalm/issues/NonInvariantDocblockPropertyType/

2021-04-10 23:46 UTC, GrahamCampbell commented on app/Http/Middleware/TrustProxies.php
> +     * @var int|string|null
But we are not that type. We are only an integer.

2021-04-11 04:42 UTC, andriichuk commented on app/Http/Middleware/TrustProxies.php
> +     * @var int|string|null
Ok, reverted. Thanks

2021-04-11 16:09 UTC, closed without merging