Remove axios due to high severity security issue
laravel/laravel pull request #6439
Opened 2024-08-13 04:17 UTC by kejedi

Axios is a dangerous package to include by default.

Here is the latest NPM audit report:

```
# npm audit report

axios  >=1.3.2
Severity: high
Server-Side Request Forgery in axios - https://github.com/advisories/GHSA-8hc4-vh64-cxmj
fix available via `npm audit fix --force`
Will install axios@1.3.1, which is a breaking change
node_modules/axios

1 high severity vulnerability
```

We don't need axios, we can use native `fetch`.

This also cleans the `resources` folder, as the extra `bootstrap.js` file was always confusing. Now the `app.js` file is empty just like `app.css`.

2024-08-13 09:45 UTC, GrahamCampbell requested changes
This change is incorrect. The latest version of axios has no known vulnerabilities.

2024-08-13 10:01 UTC, kejedi commented
> This change is incorrect. The latest version of axios has no known vulnerabilities.

Ok I guess npm audit is wrong and the open PR currently in the axios repo to fix the issue is there for no reason.

2024-08-13 11:29 UTC, GrahamCampbell commented
I believe the CVE was initially incorrectly filed without an upper-bound, and then your npm has cached the bad entry.

2024-08-13 11:58 UTC, kejedi commented
> I disagree this is high risk

My cats breath smells like cat food

2024-08-13 17:13 UTC, taylorotwell commented
Will keep an eye on this but don't see an emergency need to remove axios as the library is still maintained and receiving security fixes.

2024-08-13 17:13 UTC, closed without merging

2024-08-13 19:42 UTC, laserhybiz commented
v1.7.4 released

2024-08-16 08:24 UTC, kejedi commented
> v1.7.4 released

yup, good on you for the PR.

glad they resolved the issue quickly and Taylor was right to hold out in favour of a security patch.